### ISSUE TITLE
Feedback about changelog

### ISSUE THREAD

**Issue by valeriocos** [Bitergia/release-tools#14]
I have used the changelog for this PR: https://github.com/chaoss/grimoirelab-elk/pull/827
Please, find below the feedback:

Overall the instructions were clear. I had to restart the script since the default editor was vim, thus I followed the troubleshooting section: https://github.com/Bitergia/release-tools#how-can-i-change-the-default-editor-used-by-changelog

In the specific case of https://github.com/chaoss/grimoirelab-elk/pull/827, I had to create an issue to fill the attribute `issue`. Thus, I understand the changelog doesn't cover the case where there is a pull request not linked to an issue. This may be a problem since not all contributions pass through a issue -> pull request workflow.

I filled the `notes` with a content similar to the commit message, I don't know if this is OK or not. It would be great to add to the documentation some good examples of release notes.

Part of the attributes in the entry seem to force the user to copy/paste some info from the original issue (attributes `title` and `issue`) or commit info (`author`). I don't know if there is a way to automate this.

I would like to know the difference about the changelog approach and the adoption of a pull request template.

Thanks

**Comment by sduenas** [comment]
> I have used the changelog for this PR: [chaoss/grimoirelab-elk#827](https://github.com/chaoss/grimoirelab-elk/pull/827)
> Please, find below the feedback:
> 
> Overall the instructions were clear. I had to restart the script since the default editor was vim, thus I followed the troubleshooting section: https://github.com/Bitergia/release-tools#how-can-i-change-the-default-editor-used-by-changelog
> 
> In the specific case of [chaoss/grimoirelab-elk#827](https://github.com/chaoss/grimoirelab-elk/pull/827), I had to create an issue to fill the attribute `issue`. Thus, I understand the changelog doesn't cover the case where there is a pull request not linked to an issue. This may be a problem since not all contributions pass through a issue -> pull request workflow.

It's not a problem. You can leave the field empty.

> 
> I filled the `notes` with a content similar to the commit message, I don't know if this is OK or not. It would be great to add to the documentation some good examples of release notes.
> 

In the documentation, in the workflow section we say:
```
The notes should explain the change to a reader who has zero context about software details.
```

So usually the same commit message won't work because in a good commit message we should explain the reason of the change and why it was changed that way. In any case, I agree with you we should write some good examples, but I was waiting to do that maybe in GrimoireLab if we decide to adopt this tool.

For your case, I'd would write something like:

```
Meetup provides geolocation data for their events but in some cases this information is not available. 
On these cases, the library failed without handling the error when it was trying to process the data. To fix this, the library does not process this data anymore when it is not present in the original event and is set to empty in the enriched item.
```

By the way, I see there's a reference to chaoss/grimoirelab-perceval#637. For that case, I don't think is needed to write a changelog entry because it doesn't affect to its behaviour. I would like to write also some guidelines of this but in GrimoireLab, something like this:

https://docs.gitlab.com/ee/development/changelog.html#what-warrants-a-changelog-entry

> Part of the attributes in the entry seem to force the user to copy/paste some info from the original issue (attributes `title` and `issue`) or commit info (`author`). I don't know if there is a way to automate this.
> 

Some of these values can be passed using the command line, so there's room for automating it. In any case, the tittle, as the notes shouldn't be the same as in the commit message because the idea is a end user would be able to read this.

> I would like to know the difference about the changelog approach and the adoption of a pull request template.
> 

Pull requests depends on GitHub. Changelog is more generic and it can be used everywhere. If we move to GitLab that approach with templates will fail and we would have to retool everything.

I took the idea from people in GitLab.  In this ticket there are some references to the brainstorming process and how they ended using this approach.

https://github.com/chaoss/grimoirelab/issues/241

> Thanks

Thanks for using the tool.

**Comment by valeriocos** [comment]
> So usually the same commit message won't work because in a good commit message we should explain the reason of the change and why it was changed that way.

I understand that the same should happen for the release note, but without adding technical details. I understand that some background concepts are assumed to be known (e.g., `enriched item`) when writing the release note.

> Pull requests depends on GitHub. Changelog is more generic and it can be used everywhere. If we move to GitLab that approach with templates will fail and we would have to retool everything.

I understand your point, however I hope you understand also mine. The release tool is an extra step between a contributor and the code. IMHO the more transparent for him, the better (maybe this will be achieved in later iterations of the tools).

> Thanks for using the tool.

You're welcome

**Comment by sduenas** [comment]
> > So usually the same commit message won't work because in a good commit message we should explain the reason of the change and why it was changed that way.
> 
> I understand that the same should happen for the release note, but without adding technical details. I understand that some background concepts are assumed to be known (e.g., `enriched item`) when writing the release note.
> 

Release notes are generated using the changelog entries automatically. That's why the changelog entries should be written in that way.

Ofc there are some concepts that people should understand. Also, if there's a change in the API that would be contemplated in the changelog so people can understand how to use it.

> > Pull requests depends on GitHub. Changelog is more generic and it can be used everywhere. If we move to GitLab that approach with templates will fail and we would have to retool everything.
> 
> I understand your point, however I hope you understand also mine. The release tool is an extra step between a contributor and the code. IMHO the more transparent for him, the better (maybe this will be achieved in later iterations of the tools).
> 

I think is the same in the end. The changelog entries are based on a template. I don't really mind how the contributor creates it while it is included in the PR. If the contributor needs to fill a template when they create the PR, what's the difference with adding that info to a file before summiting a PR?

I know it's a step more but I don't see much difference on having a template in a PR than uploading a file with it. The idea in the end is to have better code.

**Comment by valeriocos** [comment]
> I think is the same in the end. 

The goal is the same

> The changelog entries are based on a template. I don't really mind how the contributor creates it while it is included in the PR. If the contributor needs to fill a template when they create the PR, what's the difference with adding that info to a file before summiting a PR?

Possible differences are listed below.

- With a template everything happens in the same UI.
- With a template there is no assumption on the expertise of the contributor. E.g. some contributors may not know how to use the vim/nano editor or they may have problems installing the release tool.
- With a template, edit on the notes (or other attributes) are more agile since are done directly in the UI. The contributor isn't required to know some Git commands to update the text (e.g., force push, squash).
- With a template, the maintainer can see the content in the body of the PR. If needed, the maintainer can directly edit the text.

> I know it's a step more but I don't see much difference on having a template in a PR than uploading a file with it.

I understand. I hope the tool will get tons of feedback from developers with different expertise. This will probably help clarifying this point (if needed).

> The idea in the end is to have better code.

At least we agree on this (that's something ^^).

**Comment by sduenas** [comment]
I understand your point but I don't think these are good examples.

I assume that if someone is contributing, in the case of GrimoireLab, it's because they have enough knowledge to understand python code, to use an editor to develop, to use git to create commits and push them to a remote repository, etc. So, I don't think contributors will be in the same group of people you are mentioning above.

If they are able to contribute with a PR I understand they would also be able to do all what you commented above.

As I said, `changelog` helps to create an entry file that will be used by the rest of the chain to generate a new release. But let's forget about that, let's pretend we are using a template to include this kind of information. Can you explain how this will be used to generate a new release?

**Comment by valeriocos** [comment]
> I assume that if someone is contributing, in the case of GrimoireLab, it's because they have enough knowledge to understand python code, to use an editor to develop, to use git to create commits and push them to a remote repository, etc. So, I don't think contributors will be in the same group of people you are mentioning above.

The assumptions you mention target some specific contributor profiles. Thus, contributors that don't meet these assumptions will probably find a barrier to contribute.

> Can you explain how this will be used to generate a new release?

The question is a bit out of focus. I have evaluated only the changelog, and I'm giving feedback only on the changelog, thus the question should focus on how the use of templates would help to generate the release notes.

I would use a bot (or a script) that leverages on the API to generate the release notes.

**Comment by sduenas** [comment]
The question is not out of focus because everything is part of a workflow that I described in chaoss/grimoirelab#241. It's also described in [README](https://github.com/Bitergia/release-tools#workflow).

Without that context it's impossible to understand why use files instead of templates. The files have a reason and a purpose.

**Comment by valeriocos** [comment]
I see. Can you describe which kind of feedback you expect to evaluate the changelog?

**Comment by sduenas** [comment]
The feedback you provided is very useful. Specially because you tested it following the documentation. Your comments about future improvements are very valuable too. I'll open tickets with some of the features you mention.

**Comment by sduenas** [comment]
Tickets with feature requests were already opened. Nothing else to discuss here.
