### ISSUE TITLE
Feedback on release tools and workflow

### ISSUE THREAD

**Issue by valeriocos** [Bitergia/release-tools#16]
I have tested the workflow on ELK (https://github.com/chaoss/grimoirelab-elk). 
Overall, the steps detailed in the README are clear and the tools easy to use. 

Find below some comments.

**changelog**
I asked some contributors to write a summary of their changes, which are available at https://github.com/chaoss/grimoirelab-elk/blob/master/releases/0.72.0.md. As you can see, the level of details of the changes isn't uniform.

 - suggestion: constrain the length of notes to a min and max number of characters/words. From the examples above 20/30 words or 200-300 characters seem to be good ranges.

One of the changes was breaking the format of the yml file (ref [here](https://github.com/chaoss/grimoirelab-elk/commit/968cf10e59a9c9d3c5c89da5da7d29bca2036726)) due to a missing `>` afters `notes:`

- suggestion: constrain the inclusion of `>` for each change. 

To target the two suggestions above, it may be worth to include a validation step of the change after its creation or before running the semverup.

**semverup**
Due to the error reported above (ref [here](https://github.com/chaoss/grimoirelab-elk/commit/968cf10e59a9c9d3c5c89da5da7d29bca2036726)), the semverup was failing (I'm not able to recover the error trace, but it is probably related to method [read_unreleased_changelog_entries](https://github.com/Bitergia/release-tools/blob/master/release_tools/semverup.py#L181)).
After fixing the error, the semverup worked fine.

**notes**
Clean executions worked fine.

I bumped into an error when re-running the script and trying to create a file note with a name equal to an existing file in the target folder. Deleting the existing file manually solved the problem. By inspecting the code I see that the flag `overwrite` could have been used.

- suggestion: improve the documentation at https://github.com/Bitergia/release-tools#notes to include an example with the flag `overwrite`.

When running the script without flag `news` on a repo that doesn't include a `NEWS` file, we end up with a notes file and no `NEWS`. This state can break the workflow, since the publish phase requires a NEWS file (https://github.com/Bitergia/release-tools/blob/master/release_tools/publish.py#L143).

**publish**
Clean executions worked fine.

I bumped into an error when re-running the script (due to some problems originated from the error reported above, ref [here](https://github.com/chaoss/grimoirelab-elk/commit/968cf10e59a9c9d3c5c89da5da7d29bca2036726)) since the tag and commit were already created. The problem was fixed by using some Git commands (e.g, git reset, git tag -d)

It would be useful to have a command line option to undo the effects of the last publish execution (the ones executed without flags). This option may be useful for the other steps of the workflow.

To avoid messing the commit history of a remote repository, I would suggest to split the **publish** and **push** actions into two different commands. The push action should include a step to force the user to review what it's going to be committed. In case the user isn't happy with the result, the script should offer the possiblity to undo the effects of the last publish execution.

**workflow**
The files produced by the release tools don't cover all changes that occurred in a repo. This may be somehow demotivating for external contributors, since their contribution is hidden.

It may be convenient to complement the outcome of the release tools with a new file which provides insights about the single commits. Examples of possible results could be:
- https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md
- https://github.com/fossology/fossology/releases

**Comment by sduenas** [comment]
Thanks for your feedback. My comments in line.

> I have tested the workflow on ELK (https://github.com/chaoss/grimoirelab-elk).
> Overall, the steps detailed in the README are clear and the tools easy to use.
> 
> Find below some comments.
> 
> **changelog**
> I asked some contributors to write a summary of their changes, which are available at https://github.com/chaoss/grimoirelab-elk/blob/master/releases/0.72.0.md. As you can see, the level of details of the changes isn't uniform.
> 
>     * suggestion: constrain the length of notes to a min and max number of characters/words. From the examples above 20/30 words or 200-300 characters seem to be good ranges.
> 

I think it's not a matter of length. It's more about content. The comment should explain in a general way why the changes were needed and what the new functionality does. I agree we don't need long explanations but I won't to limit the number of characters in the tool. Other people might use it and their requirements could be different. I think a better idea would be to add some checks in CI.

> 
> One of the changes was breaking the format of the yml file (ref [here](https://github.com/chaoss/grimoirelab-elk/commit/968cf10e59a9c9d3c5c89da5da7d29bca2036726)) due to a missing `>` afters `notes:`
> 
>     * suggestion: constrain the inclusion of `>` for each change.
> 
> 

YAML format supports many ways to add paragraphs or tests, so not only the option with '>' is valid. 

> To target the two suggestions above, it may be worth to include a validation step of the change after its creation or before running the semverup.
> 

Yes. This is a better idea. We can check the contents of the entry before `changelog` writes it. I've opened a ticket about this in (#17).

Also, take into account contributors can create this file manually. I suggest to add a check in CI to verify the new entry added.

>[...]
>
>**notes**
> Clean executions worked fine.
> 
> I bumped into an error when re-running the script and trying to create a file note with a name equal to an existing file in the target folder. Deleting the existing file manually solved the problem. By inspecting the code I see that the flag `overwrite` could have been used.
> 
>     * suggestion: improve the documentation at https://github.com/Bitergia/release-tools#notes to include an example with the flag `overwrite`.
> 

Ok! We'll add a comment including that usage.

> 
> When running the script without flag `news` on a repo that doesn't include a `NEWS` file, we end up with a notes file and no `NEWS`. This state can break the workflow, since the publish phase requires a NEWS file (https://github.com/Bitergia/release-tools/blob/master/release_tools/publish.py#L143).
> 

I did this on purpose. The idea is that after the release notes are generated the maintainer would want to review and modified them, if needed. After that, included them in the NEWS file, so he or she don't have to modify two files.

I think we should add a new assumption in the documentation (https://github.com/Bitergia/release-tools/#workflow) saying NEWS file should be available.

> **publish**
> Clean executions worked fine.
> 
> I bumped into an error when re-running the script (due to some problems originated from the error reported above, ref [here](https://github.com/chaoss/grimoirelab-elk/commit/968cf10e59a9c9d3c5c89da5da7d29bca2036726)) since the tag and commit were already created. The problem was fixed by using some Git commands (e.g, git reset, git tag -d)
> 
> It would be useful to have a command line option to undo the effects of the last publish execution (the ones executed without flags). This option may be useful for the other steps of the workflow.
> 

For the first implementation I decided not to do it because it's complicated. I've opened a ticket (#18) to add this feature in 'publish' tool. As you explain below it would be also interesting to add this functionality as an option to the command to revert the changes.

> To avoid messing the commit history of a remote repository, I would suggest to split the **publish** and **push** actions into two different commands. The push action should include a step to force the user to review what it's going to be committed. In case the user isn't happy with the result, the script should offer the possiblity to undo the effects of the last publish execution.

This is intended using `--only-push` together with `--push`. It's in the documentation but we should clarify. We can decide to do it in a separate tool too. 

> 
> **workflow**
> The files produced by the release tools don't cover all changes that occurred in a repo. This may be somehow demotivating for external contributors, since their contribution is hidden.
> 

The idea is to cover all the changes that can affect the user of the software, as is described in https://docs.gitlab.com/ee/development/changelog.html#what-warrants-a-changelog-entry . That would be part of GrimoireLab. Other people using these tools can have different requirements.

Currently, the only way to see the contributions is in the git log, and people didn't stop contributing, so I don't think this will be the case in the short term.
